services:
  asas-dev-db:
    image: postgres:17.5
    container_name: asas-dev-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev_db:/var/lib/postgresql/data

volumes:
  dev_db:

